default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost
  port: 5432

development:
  <<: *default
  database: annuaire_cmda_project_development

test:
  <<: *default
  database:  annuaire_cmda_project_test

production:
  <<: *default
  database:  annuaire_cmda_project_production
  username: cmda_project_root
  password: <%= ENV['CMDA_PROJECT_DATABASE_PASSWORD'] %>
